
DROP TABLE IF EXISTS user;
CREATE TABLE user (
    id VARCHAR(10) NOT NULL,
    name VARCHAR(100) NOT NULL,
    user_name VARCHAR(100) NOT NULL,
    password VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
  );
